name: Doc Deploy

on:
  push:
    branches:
      - gh-page
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mattnotmitt/doxygenize@1.6.3
        with:
          doxygenconf: ./RayLib_SHMUP/doc/Raylib
          htmloutput: ./html/
