name: Doc Deploy

on:
  push:
    branches:
      - documentation
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mattnotmitt/doxygen-action@1.9.4
        with:
          doxyfile-path: ./RayLib_SHMUP/doc/Raylib.doxy
          working-directory: ./RayLib_SHMUP
          enable-latex: false
