name: Doc Deploy

on:
  push:
    branches:
      - master
      - documentation
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      - uses: JesseTG/rm@v1.0.0
        with:
          path: "def/doxygen.def"
      - uses: actions/checkout@v2
        with:
          ref: documentation
      - uses: langroodi/doxygenize@v1.6.3
        with:
          doxygenconf: ./RayLib_SHMUP/doc/Raylib.doxy
          htmloutput: ./html/
