- name: Doxygen Action
# You may pin to the exact commit or the version.
# uses: mattnotmitt/doxygen-action@e13253538ce85a582a7b09338d541740c0f8d923
uses: mattnotmitt/doxygen-action@1.9.4
with:
	# Path to Doxyfile
	doxyfile-path: RayLib_SHMUP/doc/Raylib.doxy
	# Working directory
	working-directory: RayLib_SHMUP/doc/
	# Generate latex documentation
	## enable-latex: # optional
	# Extra alpine packages for the build environment
	## additional-packages: # optional, default is 
