name: Push to documentation

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: exions/merge-upstream@v1
        with:
          upstream-branch: master
          branch: documentation
          token: ${{ github.token }}
